# ------------------------------------------------------------
# Sample data for testing generated by ChatGPT
# ------------------------------------------------------------

sample_students_data = {
    "students": [
        {
            "id": 1,
            "first_name": "Jordan",
            "last_name": "Thompson",
            "email": "jthompson@northeastern.edu",
            "major": "Computer Science",
            "minor": "Applied Mathematics",
            "expected_grad_year": 2026,
            "profile_manager": {
                "id": 1,
                "first_name": "Sarah",
                "last_name": "Patel",
                "email": "s.patel@northeastern.edu"
            }
        },
        {
            "id": 2,
            "first_name": "Maya",
            "last_name": "Chen",
            "email": "mchen@northeastern.edu",
            "major": "Accounting & Finance",
            "minor": None,
            "expected_grad_year": 2025,
            "profile_manager": {
                "id": 2,
                "first_name": "Samantha",
                "last_name": "Keller",
                "email": "s.keller@northeastern.edu"
            }
        },
        {
            "id": 3,
            "first_name": "Ethan",
            "last_name": "Hunt",
            "email": "ehunt@northeastern.edu",
            "major": "Mechanical Engineering",
            "minor": "Physics",
            "expected_grad_year": 2024,
            "profile_manager": {
                "id": 1,
                "first_name": "Sarah",
                "last_name": "Patel",
                "email": "s.patel@northeastern.edu"
            }
        },
        {
            "id": 4,
            "first_name": "Diana",
            "last_name": "Prince",
            "email": "dprince@northeastern.edu",
            "major": "Marketing",
            "minor": None,
            "expected_grad_year": 2025,
            "profile_manager": {
                "id": 2,
                "first_name": "Samantha",
                "last_name": "Keller",
                "email": "s.keller@northeastern.edu"
            }
        }
    ]
}
